### PR TITLE
Add header row to excell sheet

### PR DESCRIPTION
**Pull request by HassenPy**
added header row to the spreadsheet.
added google sheets api instructions to readme.

### CODE REVIEW

**Comment by AnamikaD** [comment]
@HassenPy do we need to add Google auth?
The steps that I followed:
export SHEET_ID='SHEET ID';
NODE_GITHUB_TOKEN=<token> node index.js

**Comment by AnamikaD** [comment]
Update: I checked through the steps. I would follow that. Nice job @HassenPy ! Thank you so much :)

**Comment by HassenPy** [comment]
@AnamikaD , follow the new instructions and tell me if anything needs clarification.

**Comment by AnamikaD** [comment]
@HassenPy Thank you so much! I followed every step and still unable to publish it on excel.

**Comment by HassenPy** [comment]
try delete any file previously generated by the script, getting any errors?

**Comment by AnamikaD** [comment]
@auremoser  Hassen's script is working great!! Thank you Hassen :D

**Comment by auremoser** [comment]
Thank you so much @HassenPy !

**Pull request merged**
