### PR TITLE
Create merged json

### PR DESCRIPTION
**Pull request by ArthurSampaio**
Hi aurelia, 
the primary function of this code is concatenate all the json in /data. The outcome is a valid json (see in: http://jsonlint.com/  for checks) who contains a list of jsons. If you have more specification to do, just tell me.

### CODE REVIEW

**Comment by auremoser** [comment]
Very cool @ArthurSampaio !!! Thank you!

Would you also mind updating the README with details about your script: what it does, how to run it, and where the output file should appear (which directory, with what name)?

That would be great!

**Comment by ArthurSampaio** [comment]
It's done @auremoser ! Need something else? 
=]

**Comment by auremoser** [comment]
Amazing @ArthurSampaio ! Thank you so much!

**Comment by auremoser** [comment]
OH also @ArthurSampaio , do you have a Twitter account? I would love to thank you publicly for your PR :).

**Comment by ArthurSampaio** [comment]
Yeah, i have but yeah, i have but im not using it at last months <@ASampaioX> . I'm stay so happy because you like my PR, this is more important... btw dont need me thank, just keep my name in your mind. hahaha

**Pull request merged**
