### PR TITLE
Adding title to the Excel Sheet

### PR DESCRIPTION
**Pull request by AnamikaD**
@HassenPy As per your suggestion, I added the code. I am not sure whether it is working!! Can you please confirm?
Also, I did export the sheet ID.
The total events: 548

### CODE REVIEW

**Comment by HassenPy** [comment]
okey, i ll test this late today.

**Comment by AnamikaD** [comment]
Thanks Hassen! Do we need to add Google auth? I didn't add that.

**Comment by HassenPy** [comment]
hey, i wasn't sure how to push changes to an already made PR, i made another one but also included your commits, you might wanna close this too.

**Comment by AnamikaD** [comment]
Ya closing! thanks Hassen!

**Pull request closed without merging**
